<?php
/**
 * Plugin Name: WooCommerce AI Product Advisor
 * Description: Your AI co-pilot for WooCommerce product listings. Reviews your catalog, recommends targeted improvements to your products, and lets you apply them in one click.
 * Version: 1.0-beta
 * Author: Automattic
 * Requires at least: 6.8
 * Requires PHP: 7.4
 * Requires Plugins: woocommerce
 * WC requires at least: 10.5
 * Text Domain: wcai-pa
 *
 * @package WCAI_PA
 */

defined( 'ABSPATH' ) || exit;

define( 'WCAI_PA_VERSION', '1.0-beta' );
define( 'WCAI_PA_FILE', __FILE__ );
define( 'WCAI_PA_PATH', plugin_dir_path( __FILE__ ) );
define( 'WCAI_PA_URL', plugin_dir_url( __FILE__ ) );

// Prefer the Jetpack Autoloader (generated by automattic/jetpack-autoloader) so that
// Jetpack packages are version-resolved across every plugin on the site. Fall back
// to the standard Composer autoloader if the Jetpack one has not been generated yet.
$wcai_pa_autoloader = WCAI_PA_PATH . 'vendor/autoload_packages.php';
if ( is_readable( $wcai_pa_autoloader ) ) {
	require_once $wcai_pa_autoloader;
} else {
	require_once WCAI_PA_PATH . 'vendor/autoload.php';
}

WCAI_PA\Connection\Connection::bootstrap();

add_action( 'plugins_loaded', array( 'WCAI_PA\\Plugin', 'instance' ) );

if ( defined( 'WP_DEBUG' ) && WP_DEBUG && defined( 'WP_CLI' ) && WP_CLI ) {
	require_once WCAI_PA_PATH . 'dev/cli-bootstrap.php';
}

register_activation_hook( __FILE__, array( 'WCAI_PA\\Plugin', 'activate' ) );
register_deactivation_hook( __FILE__, array( 'WCAI_PA\\Plugin', 'deactivate' ) );
