<?php
/**
 * Plugin Name: WooCommerce AI Product Advisor
 * Plugin URI: https://github.com/woocommerce/woocommerce-ai-product-advisor
 * Description: Your AI co-pilot for WooCommerce product listings. Reviews your catalog, recommends targeted improvements to your products, and lets you apply them in one click.
 * Version: 1.0-beta
 * Author: Automattic
 * Author URI: https://woocommerce.com/
 * Developer: Automattic
 * Developer URI: https://woocommerce.com/
 * Requires at least: 6.8
 * Tested up to: 6.8
 * Requires PHP: 7.4
 * Requires Plugins: woocommerce
 * WC requires at least: 10.5
 * WC tested up to: 10.7
 * Text Domain: wcai-pa
 * Domain Path: /languages
 * License: GNU General Public License v3.0
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 *
 * @package WCAI_PA
 */

defined( 'ABSPATH' ) || exit;

define( 'WCAI_PA_VERSION', '1.0-beta' );
define( 'WCAI_PA_FILE', __FILE__ );
define( 'WCAI_PA_PATH', plugin_dir_path( __FILE__ ) );
define( 'WCAI_PA_URL', plugin_dir_url( __FILE__ ) );

// Prefer the Jetpack Autoloader (generated by automattic/jetpack-autoloader) so that
// Jetpack packages are version-resolved across every plugin on the site. Fall back
// to the standard Composer autoloader if the Jetpack one has not been generated yet.
$wcai_pa_autoloader = WCAI_PA_PATH . 'vendor/autoload_packages.php';
if ( is_readable( $wcai_pa_autoloader ) ) {
	require_once $wcai_pa_autoloader;
} else {
	require_once WCAI_PA_PATH . 'vendor/autoload.php';
}

WCAI_PA\Connection\Connection::bootstrap();

add_action(
	'before_woocommerce_init',
	function () {
		if ( class_exists( '\Automattic\WooCommerce\Utilities\FeaturesUtil' ) ) {
			\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, true );
			\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'cart_checkout_blocks', __FILE__, true );
		}
	}
);

add_action( 'plugins_loaded', array( 'WCAI_PA\\Plugin', 'instance' ) );

if ( defined( 'WP_DEBUG' ) && WP_DEBUG && defined( 'WP_CLI' ) && WP_CLI && file_exists( WCAI_PA_PATH . 'dev/cli-bootstrap.php' ) ) {
	require_once WCAI_PA_PATH . 'dev/cli-bootstrap.php';
}

register_activation_hook( __FILE__, array( 'WCAI_PA\\Plugin', 'activate' ) );
register_deactivation_hook( __FILE__, array( 'WCAI_PA\\Plugin', 'deactivate' ) );
